config/routes.rb
Jstecaj::Application.routes.draw do
  resources :images

  resources :pages
  
  match "/login" => "home#login", :via => [:get]
  root :to => 'home#index'

  get "home/index"

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :images
  has_many :pages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
  
  helper_method :current_user
  def current_user
    session_current_user ||= User.find(session[:user])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def login
    if params[:user]
      session[:user] = User.find_or_create_by_username(params[:user]).id
    
      respond_to do |format|
        format.html { redirect_to pages_url }
        format.json  { render :json => "OK".to_json, :callback => params[:callback] }
      end
    else
      respond_to do |format|
        format.html
      end
    end
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.xml
  def index
    @images = current_user.images.all
    
    @images_json = []
    @images.each do |image|
      @images_json.push({
        :id => image.id,
        :url => image.url
      })
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @images_json, :callback => params[:callback] }
    end
  end

  # GET /images/1
  # GET /images/1.xml
  def show
    @image = current_user.images.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @image, :callback => params[:callback] }
    end
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    @image = current_user.images.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = current_user.images.find(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    @image = current_user.images.build(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to(images_url, :notice => 'Image was successfully created.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = current_user.images.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to(@image, :notice => 'Image was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = current_user.images.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(images_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.xml
  def index
    @pages = current_user.pages.all
    
    @pages_json = []
    @pages.each do |page|
      @pages_json.push({
        :id => page.id,
        :title => page.title
      })
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @pages_json, :callback => params[:callback] }
    end
  end

  # GET /pages/1
  # GET /pages/1.xml
  def show
    @page = current_user.pages.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @page, :callback => params[:callback] }
    end
  end

  # GET /pages/new
  # GET /pages/new.xml
  def new
    @page = current_user.pages.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = current_user.pages.find(params[:id])
  end

  # POST /pages
  # POST /pages.xml
  def create
    @page = current_user.pages.build(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to(pages_url, :notice => 'Page was successfully created.') }
        format.xml  { render :xml => @page, :status => :created, :location => @page }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.xml
  def update
    @page = current_user.pages.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to(@page, :notice => 'Page was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.xml
  def destroy
    @page = current_user.pages.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to(pages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/login.haml
= form_tag "/login", :method => "get" do
  Username:
  = text_field_tag "user"
  %br
  = submit_tag "Prijava"
  

app/views/images/_form.html.haml
= form_for @image do |f|
  -if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/index.html.haml
%h1 Listing images

%table
  %tr
    %th User
    %th Url
    %th
    %th
    %th

  - @images.each do |image|
    %tr
      %td= image.user_id
      %td= image.url
      %td= link_to 'Show', image
      %td= link_to 'Edit', edit_image_path(image)
      %td= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%p#notice= notice

%p
  %b User:
  = @image.user_id
%p
  %b Url:
  = @image.url

= link_to 'Edit', edit_image_path(@image)
\|
= link_to 'Back', images_path

app/views/layouts/application.html.haml
!!!
%html
  
  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)
  
  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
      
      #user-menu
        = link_to "Login", "/login"
        = link_to "Pages", pages_path
        = link_to "Images", images_path
      
      - if show_title?
        %h1= yield(:title)
      
      = yield

app/views/pages/_form.html.haml
= form_for @page do |f|
  -if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', @page
\|
= link_to 'Back', pages_path

app/views/pages/index.html.haml
%h1 Listing pages

%table
  %tr
    %th User
    %th Title
    %th Content
    %th
    %th
    %th

  - @pages.each do |page|
    %tr
      %td= page.user_id
      %td= page.title
      %td= page.content
      %td= link_to 'Show', page
      %td= link_to 'Edit', edit_page_path(page)
      %td= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Page', new_page_path

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
%p#notice= notice

%p
  %b User:
  = @page.user_id
%p
  %b Title:
  = @page.title
%p
  %b Content:
  = @page.content

= link_to 'Edit', edit_page_path(@page)
\|
= link_to 'Back', pages_path